project:
  type: website

website:
  title: "Project1_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - exampleanalysis.qmd

bibliography: references.bib

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

